[[section]]
name = ".ovl1_bss"
vram = 0x800D69C0
size = 0x1F7E0

symbols = [
    { name = "gLoadedLevel", vram = 0x800BE500 },
    { name = "gLoadedStage", vram = 0x800BE504 },
    { name = "gLoadedRoom", vram = 0x800BE508 },
    { name = "gCurrentSaveFile", vram = 0x800D6B88 },
    { name = "gUnlockedLevel", vram = 0x800D6B90 },
    { name = "gUnlockedStage", vram = 0x800D6B94 },
    { name = "gSelectedLevel", vram = 0x800D6B98 },
    { name = "gBossCrystals", vram = 0x800D6BC0 },
    { name = "gCrystalArray", vram = 0x800D6BC8 },
    { "name" = "gCopyAbilityUnlocked", "vram" = 0x800D6C68},
    { "name" = "gCrystalShards", "vram" = 0x800D6C70},
    { "name" = "gReceivedIndex", "vram" = 0x800D6C74},
    { "name" = "gDeathLinkSwitch", "vram" = 0x800D6C78},
    { "name" = "gDarkStarUnlock", "vram" = 0x800D6C7C},
    { "name" = "gFriendUnlocked", "vram" = 0x800D6C80},
    { name = "gSave1Stage", vram = 0x800ECA0C },
    { name = "gSave2Stage", vram = 0x800ECA6C },
    { name = "gSave3Stage", vram = 0x800ECABC },
]